services:

  api:
    build:
      context: .
      dockerfile: LifeOrganizer.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Database=LifeOrganizer;Username=postgres;Password=password

  postgres:
    image: postgres:16
    container_name: lifeorganizer-postgres
    environment:
      POSTGRES_DB: LifeOrganizer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: